version: "3.1"

services:
  tgbot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    command: python app.py
    restart: always
    env_file:
      - .env
    volumes:
      - .:/src